const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, '../src/db/seed/seedToolsData.ts');
let content = fs.readFileSync(targetPath, 'utf8');

// Replace any remaining 'Free forever'
content = content.replace(/Free forever/g, 'Free tier');

const moreRealTools = [
  { name: 'LobeChat', category: 'Chatbots & General LLMs', pricing: 'free', signup_required: false, free_tier_limits: 'Modern open source chat framework with plugins and speech', export_formats: ['JSON', 'Markdown'], documentation_url: 'https://lobehub.com', trending_percent: 94, best_for: ['Modern UI', 'TTS Support', 'Plugin Ecosystem'], type: 'chat' },
  { name: 'NextChat', category: 'Chatbots & General LLMs', pricing: 'free', signup_required: false, free_tier_limits: 'Lightweight cross-platform ChatGPT web and desktop client', export_formats: ['JSON', 'Markdown'], documentation_url: 'https://nextchat.dev', trending_percent: 92, best_for: ['Lightweight Web Client', 'Vercel One-click', 'Cross Platform'], type: 'chat' },
  { name: 'Msty', category: 'Chatbots & General LLMs', pricing: 'free', signup_required: false, free_tier_limits: 'Free local and online AI client with side-by-side comparison', export_formats: ['JSON', 'Markdown'], documentation_url: 'https://msty.app', trending_percent: 90, best_for: ['Side-by-side Compare', 'Offline RAG', 'Local First'], type: 'chat' },
  { name: 'Enchanted LLM', category: 'Chatbots & General LLMs', pricing: 'free', signup_required: false, free_tier_limits: 'Native iOS and macOS client for Ollama models', export_formats: ['JSON'], documentation_url: 'https://github.com/AugustDev/enchanted', trending_percent: 88, best_for: ['Apple Native', 'iOS & Mac', 'Ollama Remote'], type: 'chat' },
  { name: 'HuggingChat', category: 'Chatbots & General LLMs', pricing: 'free', signup_required: true, free_tier_limits: 'Free access to top open source models on Hugging Face', export_formats: ['JSON'], documentation_url: 'https://huggingface.co/chat', trending_percent: 93, best_for: ['Open Source Foundation Models', 'Community Web UI', 'Web Search'], type: 'chat' },
  { name: 'Poe by Quora', category: 'Chatbots & General LLMs', pricing: 'free_tier', signup_required: true, free_tier_limits: 'Daily compute points for top LLMs and custom bot creation', export_formats: ['JSON'], documentation_url: 'https://poe.com', trending_percent: 95, best_for: ['Multi-bot Ecosystem', 'Prompt Monetization', 'Fast Switching'], type: 'chat' },
  { name: 'SillyTavern', category: 'Chatbots & General LLMs', pricing: 'free', signup_required: false, free_tier_limits: 'Advanced customizable interface for LLM roleplay and creative writing', export_formats: ['JSON', 'PNG'], documentation_url: 'https://sillytavern.app', trending_percent: 91, best_for: ['Roleplay & Lore', 'TTS & STT', 'Custom Personas'], type: 'chat' },
  { name: 'Faraday.dev', category: 'Chatbots & General LLMs', pricing: 'free', signup_required: false, free_tier_limits: 'One-click local AI character desktop runner', export_formats: ['JSON'], documentation_url: 'https://faraday.dev', trending_percent: 87, best_for: ['100% Private Offline', 'Zero Config', 'Local Characters'], type: 'chat' },
  { name: 'Gitingest', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: false, free_tier_limits: 'Replace hub with ingest to prompt-ready text prompt', export_formats: ['TXT', 'Markdown'], documentation_url: 'https://gitingest.com', trending_percent: 96, best_for: ['Git to Text', 'Prompt Ingestion', 'Zero Config'], type: 'code' },
  { name: 'Repopack', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: false, free_tier_limits: 'CLI tool to pack entire codebase into single AI-friendly file', export_formats: ['XML', 'Markdown', 'TXT'], documentation_url: 'https://repopack.com', trending_percent: 93, best_for: ['Codebase Compaction', 'Token Counts', 'Security Stripping'], type: 'code' },
  { name: 'Uptrain', category: 'Developer Tools & DevOps', pricing: 'free_tier', signup_required: false, free_tier_limits: 'Open-source LLM evaluation toolkit with 20+ pre-built checks', export_formats: ['JSON', 'HTML'], documentation_url: 'https://uptrain.ai', trending_percent: 89, best_for: ['RAG Hallucinations', 'Tone Checks', 'Root Cause Analysis'], type: 'data' },
  { name: 'Cleanlab', category: 'Data & Analytics', pricing: 'free_tier', signup_required: false, free_tier_limits: 'Automated data curation and label error detection', export_formats: ['CSV', 'Parquet'], documentation_url: 'https://cleanlab.ai', trending_percent: 90, best_for: ['Label Error Detection', 'Dataset Quality', 'Outlier Audits'], type: 'data' },
  { name: 'Great Expectations', category: 'Data & Analytics', pricing: 'free', signup_required: false, free_tier_limits: 'Open source data quality and pipeline validation library', export_formats: ['HTML', 'JSON'], documentation_url: 'https://greatexpectations.io', trending_percent: 92, best_for: ['Data Assertions', 'Automated Docs', 'CI/CD Data Testing'], type: 'data' },
  { name: 'Evidently AI', category: 'Data & Analytics', pricing: 'free', signup_required: false, free_tier_limits: 'Open-source ML and LLM observability and testing tool', export_formats: ['HTML', 'JSON'], documentation_url: 'https://evidentlyai.com', trending_percent: 91, best_for: ['Model Monitoring', 'Data Drift', 'LLM Metrics'], type: 'data' },
  { name: 'Braintrust', category: 'Developer Tools & DevOps', pricing: 'free_tier', signup_required: true, free_tier_limits: 'Free tier for evaluating AI products and logs', export_formats: ['JSON', 'CSV'], documentation_url: 'https://braintrust.dev', trending_percent: 94, best_for: ['Evals Framework', 'Prompt Playground', 'Continuous CI'], type: 'code' },
  { name: 'HoneyHive', category: 'Developer Tools & DevOps', pricing: 'free_tier', signup_required: true, free_tier_limits: 'Free developer tier for tracing AI agent workflows', export_formats: ['JSON'], documentation_url: 'https://honeyhive.ai', trending_percent: 88, best_for: ['Agent Tracing', 'Session Replay', 'Evaluation'], type: 'code' },
  { name: 'Langfuse', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: false, free_tier_limits: 'Open source LLM engineering platform for tracing and metrics', export_formats: ['JSON', 'CSV'], documentation_url: 'https://langfuse.com', trending_percent: 97, best_for: ['Open Source Observability', 'Latency Tracking', 'Cost Analytics'], type: 'code' },
  { name: 'Arize Phoenix', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: false, free_tier_limits: 'Open-source AI observability with traces and evals', export_formats: ['HTML', 'JSON'], documentation_url: 'https://phoenix.arize.com', trending_percent: 93, best_for: ['OpenInference Spans', 'Embedding Visualizer', 'Notebook Evals'], type: 'code' },
  { name: 'Trulens', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: false, free_tier_limits: 'Open source library to systematically evaluate and track LLM apps', export_formats: ['JSON', 'Streamlit'], documentation_url: 'https://trulens.org', trending_percent: 89, best_for: ['RAG Triad Verification', 'Groundedness', 'Relevance Metric'], type: 'data' },
  { name: 'Helicone', category: 'Developer Tools & DevOps', pricing: 'free_tier', signup_required: true, free_tier_limits: 'Open-source LLM observability platform with 100k free requests monthly', export_formats: ['JSON', 'CSV'], documentation_url: 'https://helicone.ai', trending_percent: 95, best_for: ['One-line Proxy', 'Cache Hits', 'Rate Limiting'], type: 'code' },
  { name: 'Portkey', category: 'Developer Tools & DevOps', pricing: 'free_tier', signup_required: true, free_tier_limits: 'AI Gateway with unified API and automatic fallbacks', export_formats: ['JSON'], documentation_url: 'https://portkey.ai', trending_percent: 92, best_for: ['AI Gateway', 'Automatic Retries', 'Prompt Management'], type: 'code' },
  { name: 'OpenPipe', category: 'Developer Tools & DevOps', pricing: 'free_tier', signup_required: true, free_tier_limits: 'Turn expensive prompt outputs into smaller fine-tuned models', export_formats: ['JSONL', 'Weights'], documentation_url: 'https://openpipe.ai', trending_percent: 90, best_for: ['Model Distillation', 'Fine-tuning Automation', 'Cost Reduction'], type: 'code' },
  { name: 'W&B Weave', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: true, free_tier_limits: 'Lightweight toolkit for tracking and evaluating LLM apps by Weights & Biases', export_formats: ['JSON', 'HTML'], documentation_url: 'https://wandb.ai/site/weave', trending_percent: 92, best_for: ['LLM Tracing', 'Scoring Functions', 'Dataset Versioning'], type: 'code' },
  { name: 'DocArray', category: 'Data & Analytics', pricing: 'free', signup_required: false, free_tier_limits: 'Open source data structure for multimodal data in Python', export_formats: ['Protobuf', 'JSON'], documentation_url: 'https://docarray.jina.ai', trending_percent: 87, best_for: ['Multimodal Vector Data', 'Embedding Arrays', 'Pydantic API'], type: 'data' },
  { name: 'Haystack', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: false, free_tier_limits: 'Open source NLP framework by deepset for building production RAG pipelines', export_formats: ['Python', 'YAML'], documentation_url: 'https://haystack.deepset.ai', trending_percent: 91, best_for: ['Modular Pipelines', 'Document Stores', 'Evaluation'], type: 'code' },
  { name: 'Mem0', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: false, free_tier_limits: 'The memory layer for personalized AI agents and assistants', export_formats: ['Python', 'JSON'], documentation_url: 'https://mem0.ai', trending_percent: 94, best_for: ['Long-term User Memory', 'Adaptive Graph', 'Agent Personalization'], type: 'data' },
  { name: 'Letta', category: 'Developer Tools & DevOps', pricing: 'free', signup_required: false, free_tier_limits: 'Open-source framework for building stateful agents with perpetual memory', export_formats: ['Python', 'Docker'], documentation_url: 'https://letta.com', trending_percent: 93, best_for: ['Stateful Agents', 'MemGPT Architecture', 'Self-editing Memory'], type: 'code' }
];

const jsonEntries = moreRealTools.map(t => '  ' + JSON.stringify(t, null, 2).split('\n').join('\n  ')).join(',\n');

content = content.trimEnd();
if (content.endsWith('];')) {
  content = content.slice(0, -2).trimEnd() + ',\n' + jsonEntries + '\n];\n';
}

fs.writeFileSync(targetPath, content, 'utf8');
console.log('Successfully wrote tools to seedToolsData.ts');
