export interface SeedTool {
  name: string;
  category: 'Coding' | 'Writing' | 'Chat' | 'Research' | 'Image' | 'Video' | 'Audio' | 'Presentations';
  pricing: 'free' | 'freemium' | 'paid';
  signup_required: boolean;
  free_tier_limits: string;
  free_tier_slide_limit?: number | null;
  export_formats: string[];
  documentation_url: string;
  trending_percent: number;
  best_for: string[];
  type?: string;
  description?: string;
}

export const TOOLS_500_DATA: SeedTool[] = [
  // ═══════════════════════════════════════════════════════════════
  // CODING (20 tools)
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Cursor',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free Hobby tier with 2,000 completions and 50 slow premium requests',
    export_formats: ['TypeScript', 'JavaScript', 'Python', 'Go', 'Rust'],
    documentation_url: 'https://docs.cursor.com',
    trending_percent: 98,
    best_for: ['AI Code Editor', 'Composer Multi-file Edit', 'VS Code Fork'],
    type: 'tool',
    description: 'The AI-first Code Editor built on a fork of VS Code with native multi-file agentic Composer.',
  },
  {
    name: 'GitHub Copilot',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 2,000 completions/month and 50 chat messages',
    export_formats: ['All Major IDE Formats', 'VS Code', 'JetBrains', 'Neovim'],
    documentation_url: 'https://docs.github.com/copilot',
    trending_percent: 95,
    best_for: ['Native GitHub Integration', 'Autocomplete', 'Enterprise Compliance'],
    type: 'tool',
    description: 'AI pair programmer developed by GitHub and OpenAI with deep repository awareness and CLI support.',
  },
  {
    name: 'Codeium',
    category: 'Coding',
    pricing: 'free',
    signup_required: true,
    free_tier_limits: 'Free forever for individual developers with unlimited autocomplete and chat',
    export_formats: ['VS Code', 'JetBrains', 'Chrome Extension', 'Eclipse'],
    documentation_url: 'https://codeium.com/docs',
    trending_percent: 92,
    best_for: ['Free Forever Autocomplete', 'Fast In-IDE Inference', '40+ IDEs'],
    type: 'tool',
    description: 'Free AI-powered code completion and intelligent in-editor assistant for over 40 programming editors.',
  },
  {
    name: 'Windsurf',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 25 prompt credits and Cascade assistant',
    export_formats: ['TypeScript', 'Python', 'React', 'Next.js'],
    documentation_url: 'https://codeium.com/windsurf',
    trending_percent: 94,
    best_for: ['Cascade Agent Flow', 'Deep Terminal Awareness', 'Next-gen IDE'],
    type: 'tool',
    description: 'The agentic IDE from Codeium that synchronizes code generation with deep workspace execution context.',
  },
  {
    name: 'Replit Agent',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free basic workspace; $20/mo Core tier for full Replit Agent deployment',
    export_formats: ['Full-stack Web App', 'Node.js', 'Python', 'Postgres'],
    documentation_url: 'https://docs.replit.com/replit-ai/agent',
    trending_percent: 91,
    best_for: ['End-to-end Web App Creation', 'Zero-setup Deployment', 'Cloud Hosting'],
    type: 'tool',
    description: 'Autonomous development agent that designs, codes, installs dependencies, and deploys full-stack apps.',
  },
  {
    name: 'Tabnine',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free basic plan with short code completions; $12/mo Pro plan for full lines',
    export_formats: ['VS Code', 'IntelliJ', 'Android Studio', 'Vim'],
    documentation_url: 'https://docs.tabnine.com',
    trending_percent: 85,
    best_for: ['Private On-Prem Hosting', 'Zero Data Retention', 'Secure Enterprise AI'],
    type: 'tool',
    description: 'Privacy-first AI code completion tool trained on permissively licensed open-source code.',
  },
  {
    name: 'Amazon CodeWhisperer',
    category: 'Coding',
    pricing: 'free',
    signup_required: true,
    free_tier_limits: 'Free for individual builders with unlimited code generation and security scans',
    export_formats: ['AWS Cloud9', 'VS Code', 'JetBrains', 'Lambda Console'],
    documentation_url: 'https://docs.aws.amazon.com/codewhisperer',
    trending_percent: 82,
    best_for: ['AWS Cloud APIs', 'Automated Security Scans', 'Enterprise IAM Integration'],
    type: 'tool',
    description: 'Amazon AI coding companion optimized for AWS API usage, IAM configurations, and cloud security.',
  },
  {
    name: 'Sourcegraph Cody',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 500 autocomplete credits and 20 chat requests/month',
    export_formats: ['VS Code', 'JetBrains', 'Neovim', 'Sourcegraph Web'],
    documentation_url: 'https://sourcegraph.com/docs/cody',
    trending_percent: 88,
    best_for: ['Monorepo Code Search', 'Context Graph Engine', 'Multi-repo Awareness'],
    type: 'tool',
    description: 'AI coding assistant that leverages Sourcegraph comprehensive code graph for multi-repository context.',
  },
  {
    name: 'Continue.dev',
    category: 'Coding',
    pricing: 'free',
    signup_required: false,
    free_tier_limits: 'Open source and 100% free; bring your own API keys or local Ollama model',
    export_formats: ['VS Code Extension', 'JetBrains Plugin'],
    documentation_url: 'https://docs.continue.dev',
    trending_percent: 90,
    best_for: ['Open Source Autopilot', 'Local LLM Inference', 'Ollama / LM Studio'],
    type: 'tool',
    description: 'Open-source AI code assistant allowing developers to connect custom models and local LLMs to VS Code.',
  },
  {
    name: 'Aider',
    category: 'Coding',
    pricing: 'free',
    signup_required: false,
    free_tier_limits: 'Open source command-line tool; bring your own LLM API key',
    export_formats: ['Git Commits', 'Terminal Diffs', 'CLI Output'],
    documentation_url: 'https://aider.chat/docs',
    trending_percent: 93,
    best_for: ['Git-integrated CLI Editing', 'Terminal Pair Programming', 'Automated Commits'],
    type: 'tool',
    description: 'Terminal-based AI pair programming tool that automatically writes clean git commit messages and diffs.',
  },
  {
    name: 'CodeGPT',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 20 daily AI code requests; custom API keys supported',
    export_formats: ['VS Code', 'Cursor Extension', 'Web Playground'],
    documentation_url: 'https://docs.codegpt.co',
    trending_percent: 78,
    best_for: ['Multi-model In-editor Chat', 'Prompt Templates', 'Custom Code Agents'],
    type: 'tool',
    description: 'VS Code extension facilitating seamless integration with OpenAI, Anthropic, and open-source models.',
  },
  {
    name: 'Blackbox AI',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free unlimited code generation online and browser extensions',
    export_formats: ['Code Snippets', 'JavaScript', 'Python', 'Java'],
    documentation_url: 'https://www.useblackbox.io/docs',
    trending_percent: 81,
    best_for: ['Fast Code Search', 'Extract Code from Video', 'Quick Snippet Generation'],
    type: 'tool',
    description: 'Fast developer search engine and code generator with built-in code extraction from videos and images.',
  },
  {
    name: 'Mutable AI',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier for small open-source repositories; paid plans for private repos',
    export_formats: ['Auto-generated Wikis', 'Markdown Docs', 'Pull Requests'],
    documentation_url: 'https://wiki.mutable.ai',
    trending_percent: 76,
    best_for: ['Automated Codebase Wikis', 'Architecture Documentation', 'CI/CD Sync'],
    type: 'tool',
    description: 'Generates Wikipedia-style documentation and architecture diagrams from your GitHub repositories.',
  },
  {
    name: 'Bito AI',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 100 AI requests/month; Team plans available',
    export_formats: ['Unit Tests', 'Code Explanations', 'Git Diffs'],
    documentation_url: 'https://docs.bito.ai',
    trending_percent: 74,
    best_for: ['Unit Test Generation', 'Code Refactoring', 'Security Vulnerability Review'],
    type: 'tool',
    description: 'In-IDE coding assistant designed for generating unit tests, code explanations, and security reviews.',
  },
  {
    name: 'AskCodi',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 50 credits/month; $10/mo premium tier',
    export_formats: ['Frontend Modules', 'SQL Queries', 'Dockerfiles'],
    documentation_url: 'https://www.askcodi.com/docs',
    trending_percent: 72,
    best_for: ['SQL Query Building', 'Regex Generation', 'Frontend Framework Helpers'],
    type: 'tool',
    description: 'AI code suite providing specialized tools for SQL generation, documentation, and frontend prototyping.',
  },
  {
    name: 'CodeSandbox AI',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free public sandboxes with basic AI assistance; $15/mo Pro',
    export_formats: ['Live Web URLs', 'React / Next.js', 'GitHub Repos'],
    documentation_url: 'https://codesandbox.io/docs',
    trending_percent: 86,
    best_for: ['Cloud Sandbox Previews', 'Collaborative Coding', 'Full-stack MicroVMs'],
    type: 'tool',
    description: 'Cloud development platform featuring instant environment spinning and AI code repair in the browser.',
  },
  {
    name: 'Qodo',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free Developer tier with automated test generation and PR reviews',
    export_formats: ['Jest / PyTest', 'GitHub PR Reviews', 'VS Code Tests'],
    documentation_url: 'https://www.qodo.ai/docs',
    trending_percent: 89,
    best_for: ['Automated Unit Tests', 'PR Integrity Verification', 'Bug Detection'],
    type: 'tool',
    description: 'Quality-first AI developer platform specializing in test suite creation and pull request verification.',
  },
  {
    name: 'Sweep',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier for public repositories; 5 monthly issues handled',
    export_formats: ['GitHub Pull Requests', 'Branch Commits'],
    documentation_url: 'https://docs.sweep.dev',
    trending_percent: 83,
    best_for: ['GitHub Issue to PR', 'Automated Bug Fixing', 'Refactoring Tasks'],
    type: 'tool',
    description: 'AI junior developer that turns GitHub issues and bug reports directly into tested pull requests.',
  },
  {
    name: 'Factory AI',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free pilot credits for developer teams; enterprise onboarding',
    export_formats: ['System Migrations', 'Full PR Workflows'],
    documentation_url: 'https://factory.ai/docs',
    trending_percent: 80,
    best_for: ['Autonomous Droids', 'Codebase Migrations', 'Enterprise Refactors'],
    type: 'tool',
    description: 'Specialized enterprise AI Droids designed to tackle long-running software engineering tasks and migrations.',
  },
  {
    name: 'Refact AI',
    category: 'Coding',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with basic completions and open-source self-hosting options',
    export_formats: ['VS Code Extension', 'JetBrains Plugin', 'Docker Container'],
    documentation_url: 'https://refact.ai/docs',
    trending_percent: 77,
    best_for: ['Self-hosted AI Engine', 'Fine-tuned Models', 'Low Latency Completions'],
    type: 'tool',
    description: 'Open-source, self-hostable AI coding assistant supporting custom fine-tuning and fine-grained data control.',
  },

  // ═══════════════════════════════════════════════════════════════
  // WRITING (15 tools)
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Jasper',
    category: 'Writing',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '7-day free trial; plans start at $39/month',
    export_formats: ['Markdown', 'Google Docs', 'Word / DOCX'],
    documentation_url: 'https://www.jasper.ai/docs',
    trending_percent: 89,
    best_for: ['Brand Voice Consistency', 'Enterprise Marketing Copy', 'Multi-channel Campaigns'],
    type: 'tool',
    description: 'Enterprise AI copy platform tailored for marketing teams with custom brand voice governance.',
  },
  {
    name: 'Copy.ai',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 2,000 words per month in chat; Pro plan with unlimited words',
    export_formats: ['Markdown', 'Rich Text', 'CSV Exports'],
    documentation_url: 'https://docs.copy.ai',
    trending_percent: 86,
    best_for: ['GTM Workflow Automation', 'Ad Copywriting', 'Cold Email Outreach'],
    type: 'tool',
    description: 'AI platform powering sales and marketing workflows with automated content generation sequences.',
  },
  {
    name: 'Grammarly',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with grammar, punctuation, and 100 AI prompt suggestions per month',
    export_formats: ['Browser Integration', 'Word Plugin', 'Desktop App'],
    documentation_url: 'https://support.grammarly.com',
    trending_percent: 94,
    best_for: ['Grammar & Tone Auditing', 'Real-time Spell Checking', 'Universal In-browser Typing'],
    type: 'tool',
    description: 'Ubiquitous writing companion providing real-time grammatical, stylistic, and tone enhancements.',
  },
  {
    name: 'Sudowrite',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free trial with 10,000 credits; plans start at $10/month',
    export_formats: ['DOCX', 'Plain Text', 'PDF'],
    documentation_url: 'https://www.sudowrite.com/guide',
    trending_percent: 84,
    best_for: ['Fiction Writing', 'Novel Plotting', 'Character Brainstorming'],
    type: 'tool',
    description: 'AI-assisted writing studio tailored for novelists and creative fiction authors with Story Engine.',
  },
  {
    name: 'Writesonic',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 25 generation credits; paid plans from $16/mo',
    export_formats: ['WordPress Push', 'HTML', 'Markdown'],
    documentation_url: 'https://docs.writesonic.com',
    trending_percent: 82,
    best_for: ['SEO Blog Articles', 'WordPress Integration', 'E-commerce Product Descriptions'],
    type: 'tool',
    description: 'AI content creation platform specialized in factual blog generation and direct CMS publication.',
  },
  {
    name: 'Rytr',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 10,000 characters per month; Unlimited at $9/month',
    export_formats: ['DOCX', 'PDF', 'Markdown'],
    documentation_url: 'https://rytr.me/resources',
    trending_percent: 79,
    best_for: ['Affordable Copywriting', 'Short-form Social Content', 'Tone Customization'],
    type: 'tool',
    description: 'Lightweight and budget-friendly AI writing assistant supporting 30+ languages and 20+ tones.',
  },
  {
    name: 'Notion AI',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Complimentary trial requests in Notion workspace; $8/mo add-on',
    export_formats: ['Notion Pages', 'Markdown', 'PDF', 'CSV'],
    documentation_url: 'https://www.notion.so/help/notion-ai',
    trending_percent: 93,
    best_for: ['Workspace Knowledge Search', 'Meeting Notes Summarization', 'Inline Page Drafting'],
    type: 'tool',
    description: 'Integrated intelligence engine inside Notion that queries company docs and drafts structured wikis.',
  },
  {
    name: 'QuillBot',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free paraphraser up to 125 words per rewrite; Premium unlocks unlimited',
    export_formats: ['DOCX', 'Chrome Extension', 'Text File'],
    documentation_url: 'https://quillbot.com/help',
    trending_percent: 88,
    best_for: ['Sentence Paraphrasing', 'Summarization Engine', 'Vocabulary Enrichment'],
    type: 'tool',
    description: 'AI paraphrasing and summarization tool designed to reword text while retaining original context.',
  },
  {
    name: 'Wordtune',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: '10 free rewrites per day and 3 AI prompts; Unlimited at $9.99/mo',
    export_formats: ['Chrome Extension', 'Web App', 'Word Plugin'],
    documentation_url: 'https://www.wordtune.com/faq',
    trending_percent: 81,
    best_for: ['Sentence Rephrasing', 'Tone Switching (Casual / Formal)', 'Length Adjustment'],
    type: 'tool',
    description: 'Context-driven rewrite tool from AI21 Labs that suggests crisp alternative phrasing for any sentence.',
  },
  {
    name: 'ProWritingAid',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 500-word checks and 10 daily rephrases',
    export_formats: ['Scrivener', 'DOCX', 'PDF', 'Google Docs'],
    documentation_url: 'https://prowritingaid.com/guide',
    trending_percent: 78,
    best_for: ['In-depth Style Reports', 'Manuscript Editing', 'Pacing & Consistency Analysis'],
    type: 'tool',
    description: 'Comprehensive writing coach and editor providing detailed reports on pacing, repetition, and readability.',
  },
  {
    name: 'Hemingway Editor',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free web version; Hemingway Editor Plus with AI features from $10/mo',
    export_formats: ['HTML', 'Markdown', 'PDF'],
    documentation_url: 'https://hemingwayapp.com',
    trending_percent: 77,
    best_for: ['Readability Grading', 'Active Voice Enforcement', 'Sentence Simplification'],
    type: 'tool',
    description: 'Renowned clarity tool highlighting complex sentences, passive voice, and readability scores.',
  },
  {
    name: 'HyperWrite',
    category: 'Writing',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 15 generations/month; $20/mo Premium plan',
    export_formats: ['Chrome Extension', 'Web Documents'],
    documentation_url: 'https://hyperwriteai.com/support',
    trending_percent: 75,
    best_for: ['Autonomous Personal Assistant', 'Browser Automation', 'Contextual Email Replies'],
    type: 'tool',
    description: 'AI writing partner featuring a browser automation assistant that executes tasks across web applications.',
  },
  {
    name: 'Anyword',
    category: 'Writing',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '7-day trial with 2,500 word credits; plans start at $39/mo',
    export_formats: ['Ad Platforms', 'CSV', 'Plain Text'],
    documentation_url: 'https://anyword.com/docs',
    trending_percent: 73,
    best_for: ['Performance Predictive Scoring', 'Data-driven Ad Copy', 'Audience Demographics Tuning'],
    type: 'tool',
    description: 'Copywriting platform that calculates predictive performance scores before you publish marketing text.',
  },
  {
    name: 'Frase',
    category: 'Writing',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '5-day trial for $1; subscription starts at $15/month',
    export_formats: ['Google Docs', 'WordPress', 'HTML'],
    documentation_url: 'https://www.frase.io/docs',
    trending_percent: 76,
    best_for: ['SEO Content Briefs', 'SERP Analysis', 'Keyword Optimization'],
    type: 'tool',
    description: 'SEO content optimization tool that analyzes top search results and guides high-ranking article generation.',
  },
  {
    name: 'Surfer SEO',
    category: 'Writing',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '7-day money-back guarantee; Essential plan from $89/mo',
    export_formats: ['Google Docs Extension', 'WordPress Plugin', 'PDF Audit'],
    documentation_url: 'https://docs.surferseo.com',
    trending_percent: 85,
    best_for: ['Real-time Content Score', 'Search Intent Guidelines', 'Internal Link Suggestions'],
    type: 'tool',
    description: 'Algorithm-driven content editor ensuring written material matches exact competitive search engine ranking factors.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAT (15 tools)
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'ChatGPT',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with GPT-4o Mini and dynamic GPT-4o access; $20/mo Plus',
    export_formats: ['JSON', 'CSV', 'PDF', 'Web Links'],
    documentation_url: 'https://chatgpt.com',
    trending_percent: 99,
    best_for: ['Consumer AI Interface', 'Canvas Coding', 'Voice Mode'],
    type: 'tool',
    description: 'OpenAI flagship conversational assistant with native voice, deep research, and Canvas capabilities.',
  },
  {
    name: 'Claude',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with Sonnet; $20/mo Pro for 5x capacity and Opus access',
    export_formats: ['JSON', 'PDF', 'Markdown', 'Artifacts Preview'],
    documentation_url: 'https://claude.ai',
    trending_percent: 98,
    best_for: ['Interactive Artifacts', 'Deep Reasoning & Analysis', 'Extended Coding Sessions'],
    type: 'tool',
    description: 'Anthropic conversational model interface renowned for nuanced writing, logic, and interactive Artifacts.',
  },
  {
    name: 'Gemini',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with Gemini 2.5 Flash; $20/mo Advanced with 2M token context',
    export_formats: ['Google Docs', 'Gmail Drafts', 'PDF', 'JSON'],
    documentation_url: 'https://gemini.google.com',
    trending_percent: 96,
    best_for: ['Google Workspace Sync', '2M Token Context Window', 'Multimodal Video Analysis'],
    type: 'tool',
    description: 'Google multimodal assistant integrated with Gmail, Drive, YouTube, and real-time Web grounding.',
  },
  {
    name: 'Perplexity',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free unlimited basic searches; $20/mo Pro with 300+ daily Pro queries',
    export_formats: ['Markdown', 'PDF', 'Shareable Links'],
    documentation_url: 'https://docs.perplexity.ai',
    trending_percent: 97,
    best_for: ['Real-time Web Citations', 'Academic Sourcing', 'Fast Fact Checking'],
    type: 'tool',
    description: 'Conversational answer engine delivering cited summaries directly extracted from the live internet.',
  },
  {
    name: 'Poe',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free daily points for popular models; $19.99/mo subscription for unlimited',
    export_formats: ['Text', 'Shareable Bots'],
    documentation_url: 'https://creator.poe.com/docs',
    trending_percent: 87,
    best_for: ['Multi-model Aggregation', 'Custom Bot Builder', 'Model Cross-comparison'],
    type: 'tool',
    description: 'Quora AI ecosystem providing unified access to Claude, GPT-4, Llama, and user-created custom bots.',
  },
  {
    name: 'Character.AI',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free unlimited chatting; $9.99/mo c.ai+ for skip queues and faster response',
    export_formats: ['Chat Logs', 'Voice Clips'],
    documentation_url: 'https://character.ai',
    trending_percent: 91,
    best_for: ['Persona Roleplay', 'Conversational Practice', 'Community Characters'],
    type: 'tool',
    description: 'Dialog platform allowing users to engage with millions of community-created AI personalities.',
  },
  {
    name: 'Mistral Le Chat',
    category: 'Chat',
    pricing: 'free',
    signup_required: true,
    free_tier_limits: 'Free access to Mistral Large, Pixtral, and Codestral without subscription fees',
    export_formats: ['Markdown', 'Code Snippets'],
    documentation_url: 'https://chat.mistral.ai',
    trending_percent: 90,
    best_for: ['European Open Weights', 'Coding Precision', 'Multilingual Dialogue'],
    type: 'tool',
    description: 'Official consumer chat interface from Mistral AI showcasing flagship open-weight frontier models.',
  },
  {
    name: 'Grok',
    category: 'Chat',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: 'Included with X Premium ($8/mo) or Premium+ subscription',
    export_formats: ['Text', 'X Posts'],
    documentation_url: 'https://x.ai',
    trending_percent: 89,
    best_for: ['Real-time Social Signals', 'Uncensored Explanations', 'News Analysis'],
    type: 'tool',
    description: 'xAI conversational engine grounded in real-time X social network data and witty perspective.',
  },
  {
    name: 'DeepSeek Chat',
    category: 'Chat',
    pricing: 'free',
    signup_required: true,
    free_tier_limits: 'Free unlimited access to DeepSeek-V3 and DeepSeek-R1 reasoning models',
    export_formats: ['Markdown', 'LaTeX', 'Code Blocks'],
    documentation_url: 'https://chat.deepseek.com',
    trending_percent: 95,
    best_for: ['Math & Logic Reasoning', 'Chain of Thought Breakdown', 'Zero-cost Frontier Model'],
    type: 'tool',
    description: 'Conversational interface for DeepSeek R1 reasoning and V3 models with explicit chain-of-thought steps.',
  },
  {
    name: 'HuggingChat',
    category: 'Chat',
    pricing: 'free',
    signup_required: false,
    free_tier_limits: 'Free and open source; powered by Hugging Face Inference Infrastructure',
    export_formats: ['Markdown', 'JSON'],
    documentation_url: 'https://huggingface.co/chat',
    trending_percent: 84,
    best_for: ['Open Source Model Switching', 'Community Presets', 'Web Search Activation'],
    type: 'tool',
    description: 'Open-source chat alternative from Hugging Face supporting Llama 3, Qwen, and Gemma models.',
  },
  {
    name: 'You.com',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free basic searches; $20/mo Pro for unlimited multi-model queries',
    export_formats: ['PDF', 'Text Snippets', 'Search Links'],
    documentation_url: 'https://you.com',
    trending_percent: 80,
    best_for: ['Productivity Search', 'Custom AI Modes', 'Code & Writing Search'],
    type: 'tool',
    description: 'Personalized search and chat assistant that synthesizes web knowledge with customizable search modes.',
  },
  {
    name: 'Phind',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free unlimited queries with Phind model; $20/mo Pro for GPT-4o & Claude 3.5',
    export_formats: ['Terminal Scripts', 'Markdown', 'Code Diffs'],
    documentation_url: 'https://www.phind.com',
    trending_percent: 88,
    best_for: ['Technical Documentation Search', 'Developer Problem Solving', 'In-depth Stack Traces'],
    type: 'tool',
    description: 'AI search engine built specifically for software engineers with deep scraping of official docs and GitHub.',
  },
  {
    name: 'Kagi',
    category: 'Chat',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '100 trial searches; subscriptions start at $5/month',
    export_formats: ['Web Summaries', 'PDF Transcripts'],
    documentation_url: 'https://help.kagi.com',
    trending_percent: 85,
    best_for: ['Ad-free Web Searching', 'Quick Webpage Summarization', 'Privacy-first Results'],
    type: 'tool',
    description: 'Premium, ad-free search engine pairing privacy guarantees with fast multi-model summarizers.',
  },
  {
    name: 'Pi',
    category: 'Chat',
    pricing: 'free',
    signup_required: false,
    free_tier_limits: 'Free conversational AI with unlimited audio and text interactions',
    export_formats: ['Audio Stream', 'Text Chat'],
    documentation_url: 'https://pi.ai',
    trending_percent: 83,
    best_for: ['Empathetic Conversation', 'Human-like Voice Synthetics', 'Daily Check-in Chats'],
    type: 'tool',
    description: 'Personal AI created by Inflection AI focusing on supportive, conversational, and voice interactions.',
  },
  {
    name: 'Cohere Coral',
    category: 'Chat',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free sandbox playground with API trial tokens; enterprise volume pricing',
    export_formats: ['JSON', 'API Responses', 'Enterprise Logs'],
    documentation_url: 'https://docs.cohere.com/docs/coral',
    trending_percent: 82,
    best_for: ['Enterprise Knowledge Retrieval', 'Strict Source Grounding', 'RAG Validation'],
    type: 'tool',
    description: 'Enterprise conversational assistant optimized for enterprise RAG, search citations, and document grounding.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RESEARCH (15 tools)
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Perplexity Research',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free standard search; Pro tier includes unlimited Deep Research and academic filters',
    export_formats: ['PDF', 'Markdown', 'Bibliography'],
    documentation_url: 'https://docs.perplexity.ai',
    trending_percent: 96,
    best_for: ['Autonomous Deep Research', 'Multi-source Fact Syntheses', 'Academic Citations'],
    type: 'tool',
    description: 'Autonomous research mode compiling multi-page dossiers with verified sources from 100+ websites.',
  },
  {
    name: 'Elicit',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 5,000 one-time credits; Plus plan at $10/month for 12,000 monthly credits',
    export_formats: ['CSV', 'BIBTEX', 'RIS', 'PDF Export'],
    documentation_url: 'https://support.elicit.com',
    trending_percent: 93,
    best_for: ['Systematic Literature Reviews', 'Paper Extraction Tables', 'Scientific Consensus'],
    type: 'tool',
    description: 'AI research assistant using semantic search over 200M papers to extract findings into comparative tables.',
  },
  {
    name: 'Consensus',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with unlimited basic searches and 3 Consensus Meters/month',
    export_formats: ['Citations (APA/MLA)', 'CSV', 'Markdown'],
    documentation_url: 'https://consensus.app/home/blog/docs',
    trending_percent: 90,
    best_for: ['Scientific Consensus Meter', 'Evidence-based Answers', 'Peer-reviewed Sourcing'],
    type: 'tool',
    description: 'Search engine using AI to extract verified findings from peer-reviewed scientific studies.',
  },
  {
    name: 'Scite',
    category: 'Research',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '7-day free trial; plans start at $12/month billed annually',
    export_formats: ['CSV', 'Zotero Integration', 'Mendeley Sync'],
    documentation_url: 'https://scite.ai/faq',
    trending_percent: 86,
    best_for: ['Smart Citations (Supporting/Contrasting)', 'Reference Quality Audit', 'Author Verifications'],
    type: 'tool',
    description: 'Smart citation platform categorizing whether scientific articles support, mention, or contrast findings.',
  },
  {
    name: 'Semantic Scholar',
    category: 'Research',
    pricing: 'free',
    signup_required: false,
    free_tier_limits: 'Completely free service provided by the Allen Institute for AI',
    export_formats: ['BIBTEX', 'EndNote', 'API Endpoints'],
    documentation_url: 'https://www.semanticscholar.org/product/api',
    trending_percent: 91,
    best_for: ['Free Academic Paper Index', 'Influence & Citation Graphs', 'TLDR Summaries'],
    type: 'tool',
    description: 'AI-backed research tool from Ai2 indexing over 200 million academic papers with one-sentence TLDRs.',
  },
  {
    name: 'Connected Papers',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 5 graph builds per month; Premium unlocks unlimited visual graphs',
    export_formats: ['Visual Graph PNG', 'BIBTEX', 'Paper List'],
    documentation_url: 'https://www.connectedpapers.com/about',
    trending_percent: 88,
    best_for: ['Visual Graph of Academic Fields', 'Discovering Seminal Papers', 'Prior Art Exploration'],
    type: 'tool',
    description: 'Visual citation mapper plotting connected scientific papers in an interactive relational graph.',
  },
  {
    name: 'Litmaps',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 1 visual map and 20 articles per search; Pro at $10/month',
    export_formats: ['BIBTEX', 'RIS', 'PNG', 'SVG'],
    documentation_url: 'https://www.litmaps.com/guide',
    trending_percent: 84,
    best_for: ['Literature Citation Trajectory', 'Citation Alerts', 'Chronological Paper Trees'],
    type: 'tool',
    description: 'Interactive visual discovery tool for research that maps citation trees over chronological timelines.',
  },
  {
    name: 'ResearchRabbit',
    category: 'Research',
    pricing: 'free',
    signup_required: true,
    free_tier_limits: 'Completely free for academic researchers and students worldwide',
    export_formats: ['Zotero Sync', 'BIBTEX', 'RIS', 'Interactive Maps'],
    documentation_url: 'https://www.researchrabbit.ai',
    trending_percent: 89,
    best_for: ['Spotify for Papers', 'Zotero Bidirectional Sync', 'Author Network Mapping'],
    type: 'tool',
    description: 'Revered as the Spotify of research, building personalized collections and visual author networks for free.',
  },
  {
    name: 'Scholarcy',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free browser extension with basic flashcards; Personal library from $7.99/mo',
    export_formats: ['Summary Flashcards', 'Word DOCX', 'Markdown', 'PowerPoint'],
    documentation_url: 'https://www.scholarcy.com/faq',
    trending_percent: 82,
    best_for: ['Interactive Paper Flashcards', 'Table & Figure Extraction', 'Speed Reading Research'],
    type: 'tool',
    description: 'Summarization engine converting dense PDF research papers into interactive, structured flashcard summaries.',
  },
  {
    name: 'SciSpace',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with unlimited basic queries and Copilot reading assistant; $12/mo Premium',
    export_formats: ['PDF with AI Annotations', 'Markdown', 'BIBTEX'],
    documentation_url: 'https://typeset.io/resources',
    trending_percent: 87,
    best_for: ['Chat with PDF Math/Formulas', 'Literature Matrix Generation', 'Multi-paper Comparison'],
    type: 'tool',
    description: 'End-to-end research platform enabling interactive reading and conversational breakdowns of technical papers.',
  },
  {
    name: 'Zotero',
    category: 'Research',
    pricing: 'free',
    signup_required: false,
    free_tier_limits: 'Free open-source software with 300MB free cloud storage; unlimited local storage',
    export_formats: ['BIBTEX', 'RIS', 'CSL JSON', 'APA/IEEE/Chicago'],
    documentation_url: 'https://www.zotero.org/support',
    trending_percent: 94,
    best_for: ['Reference Management', 'PDF Metadata Scraping', 'Open Source Workflow'],
    type: 'tool',
    description: 'Open-source reference manager storing metadata, PDFs, and notes with automated DOI citation ingestion.',
  },
  {
    name: 'Mendeley',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 2GB cloud library storage; institutional subscriptions',
    export_formats: ['BIBTEX', 'XML', 'Word Citation Plugin'],
    documentation_url: 'https://www.mendeley.com/guides',
    trending_percent: 83,
    best_for: ['Institutional Collaboration', 'Word Document Citations', 'Annotation Sharing'],
    type: 'tool',
    description: 'Elsevier reference management system with collaborative group annotation and MS Word plug-ins.',
  },
  {
    name: 'Iris.ai',
    category: 'Research',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: 'Institutional pilot trials available upon demonstration request',
    export_formats: ['Data Extraction Sheets', 'Structured JSON'],
    documentation_url: 'https://iris.ai/documentation',
    trending_percent: 78,
    best_for: ['R&D Systematic Filtering', 'Patent Landscape Analysis', 'Biochemical Research'],
    type: 'tool',
    description: 'Comprehensive AI workspace for scientific text processing, document filtering, and systematic patent research.',
  },
  {
    name: 'Dimensions AI',
    category: 'Research',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free open access for researchers to search publications and citations',
    export_formats: ['CSV', 'BIBTEX', 'Excel'],
    documentation_url: 'https://www.dimensions.ai/resources',
    trending_percent: 81,
    best_for: ['Grant and Funding Tracking', 'Patent Analytics', 'Clinical Trial Correlation'],
    type: 'tool',
    description: 'Linked research knowledge system connecting publications, datasets, grants, clinical trials, and patents.',
  },
  {
    name: 'Lens.org',
    category: 'Research',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free public access for academic research; commercial licenses available',
    export_formats: ['CSV', 'JSON', 'BIBTEX', 'Patent Reports'],
    documentation_url: 'https://support.lens.org',
    trending_percent: 80,
    best_for: ['Patent Citations', 'Open Science Auditing', 'Global IP Mapping'],
    type: 'tool',
    description: 'Global open discovery platform uniting over 250M scholarly works with international patent records.',
  },

  // ═══════════════════════════════════════════════════════════════
  // IMAGE (15 tools)
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Midjourney',
    category: 'Image',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: 'Subscription required; plans start at $10/month for Basic GPU hours',
    export_formats: ['PNG', 'WebP', 'High-res Upscales'],
    documentation_url: 'https://docs.midjourney.com',
    trending_percent: 98,
    best_for: ['Photorealistic Portraits', 'Cinematic Aesthetics', 'Artistic Direction'],
    type: 'tool',
    description: 'Premier generative image synthesis platform celebrated for unmatched artistic rendering and lighting fidelity.',
  },
  {
    name: 'DALL-E 3',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Included with ChatGPT Plus ($20/mo) and free daily generations via Microsoft Copilot',
    export_formats: ['PNG', 'WebP'],
    documentation_url: 'https://openai.com/dall-e-3',
    trending_percent: 95,
    best_for: ['Complex Prompt Adherence', 'In-image Typography', 'Conversational Inpainting'],
    type: 'tool',
    description: 'OpenAI text-to-image model that translates nuanced text descriptions directly into accurate images.',
  },
  {
    name: 'Stable Diffusion',
    category: 'Image',
    pricing: 'free',
    signup_required: false,
    free_tier_limits: 'Open weights available for unlimited local generation on consumer hardware',
    export_formats: ['PNG', 'Lossless Formats', 'Safetensors Models'],
    documentation_url: 'https://stability.ai/documentation',
    trending_percent: 96,
    best_for: ['Self-hosted Local Execution', 'LoRA & ControlNet Customization', 'Open Ecosystem'],
    type: 'tool',
    description: 'Stability AI open-source foundation model powering local generation with extensive community weights.',
  },
  {
    name: 'Leonardo.ai',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 150 daily generation tokens; $10/mo Apprentice plan',
    export_formats: ['PNG', 'Transparent Backgrounds', '3D Textures'],
    documentation_url: 'https://docs.leonardo.ai',
    trending_percent: 93,
    best_for: ['Game Asset Prototyping', 'Real-time Canvas Painting', 'Custom Model Training'],
    type: 'tool',
    description: 'Creative studio platform with real-time generation, inpainting canvas, and custom model fine-tuning.',
  },
  {
    name: 'Ideogram',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 10 slow generation credits daily; $8/mo Basic plan',
    export_formats: ['PNG', 'JPEG'],
    documentation_url: 'https://ideogram.ai/docs',
    trending_percent: 92,
    best_for: ['Exact Graphic Text Inscription', 'Logo & Emblem Design', 'Typography Posters'],
    type: 'tool',
    description: 'Leading generative model for rendering coherent, legible typography and graphic design layouts inside images.',
  },
  {
    name: 'Adobe Firefly',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 25 monthly generative credits; Creative Cloud integration',
    export_formats: ['PSD', 'PNG', 'SVG Vector', 'JPEG'],
    documentation_url: 'https://helpx.adobe.com/firefly',
    trending_percent: 90,
    best_for: ['Commercial Safety Indemnity', 'Generative Fill in Photoshop', 'Vector SVG Creation'],
    type: 'tool',
    description: 'Adobe commercially-safe generative AI engine trained exclusively on Adobe Stock and licensed media.',
  },
  {
    name: 'Flux',
    category: 'Image',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Flux.1 Schnell open source for local runs; API pay-per-image options',
    export_formats: ['PNG', 'WebP', 'Safetensors'],
    documentation_url: 'https://blackforestlabs.ai',
    trending_percent: 97,
    best_for: ['Photorealistic Detail', 'Finger & Hand Geometry', 'Open Weight Generation'],
    type: 'tool',
    description: 'Frontier text-to-image foundation model series from Black Forest Labs setting new visual quality benchmarks.',
  },
  {
    name: 'Playground AI',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 50 images per day; $15/mo Pro with unlimited creations',
    export_formats: ['PNG', 'Canvas Projects'],
    documentation_url: 'https://playground.com/docs',
    trending_percent: 86,
    best_for: ['Infinite Creative Canvas', 'Multi-layer Compositions', 'Quick Style Filters'],
    type: 'tool',
    description: 'Online graphic design and generative canvas allowing creators to blend and refine generated assets.',
  },
  {
    name: 'NightCafe',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: '5 free daily credits with community challenge rewards; credit packs available',
    export_formats: ['PNG', 'JPEG', 'NFT Minting'],
    documentation_url: 'https://nightcafe.studio/faqs',
    trending_percent: 81,
    best_for: ['Community Art Contests', 'Multi-algorithm Selection', 'Beginner Friendly Creation'],
    type: 'tool',
    description: 'Gamified art studio platform giving access to Stable Diffusion, DALL-E, and community challenges.',
  },
  {
    name: 'DreamStudio',
    category: 'Image',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '25 free trial credits upon sign up; $10 for 1,000 credits',
    export_formats: ['PNG', 'JPEG', 'WebP'],
    documentation_url: 'https://dreamstudio.ai/faq',
    trending_percent: 83,
    best_for: ['Direct SDXL Generation', 'Precision Seed Control', 'Weight Adjustments'],
    type: 'tool',
    description: 'Stability AI official web interface for fine-tuned generation with SDXL, SD 3, and depth guidance.',
  },
  {
    name: 'Lexica',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free search engine; 16 free generations/month; $10/mo starter',
    export_formats: ['PNG', 'Direct Download'],
    documentation_url: 'https://lexica.art/docs',
    trending_percent: 85,
    best_for: ['Prompt Inspiration Index', 'Aesthetic Character Design', 'Search by Similarity'],
    type: 'tool',
    description: 'Search engine and generative model focused on aesthetic illustrations, portrait art, and prompt discovery.',
  },
  {
    name: 'Craiyon',
    category: 'Image',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free ad-supported generation with no signup required; Pro from $5/month',
    export_formats: ['PNG', 'JPEG'],
    documentation_url: 'https://www.craiyon.com',
    trending_percent: 79,
    best_for: ['Instant No-login Generation', 'Meme Prototyping', 'Lightweight Sketches'],
    type: 'tool',
    description: 'Accessible, free web generator providing quick conceptual sketches without mandatory accounts.',
  },
  {
    name: 'Artbreeder',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 10 monthly credits; $8.99/mo Starter tier',
    export_formats: ['PNG', 'High-res Upscale'],
    documentation_url: 'https://www.artbreeder.com/about',
    trending_percent: 82,
    best_for: ['Gene-mixing Portrait Morphs', 'Collage-to-Image Canvas', 'Character Variation'],
    type: 'tool',
    description: 'Collaborative generative studio utilizing gene-mixing sliders to interpolate faces, landscapes, and paintings.',
  },
  {
    name: 'Recraft',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 50 daily generation credits; $20/mo Pro for vector export',
    export_formats: ['Clean Vector SVG', 'PNG', 'Lottie Animation'],
    documentation_url: 'https://www.recraft.ai/docs',
    trending_percent: 94,
    best_for: ['Clean Vector SVG Output', 'Design System Iconography', 'Brand Consistency Sets'],
    type: 'tool',
    description: 'Graphic design tool specifically generating clean, editable SVG vectors and consistent 3D brand assets.',
  },
  {
    name: 'Krea AI',
    category: 'Image',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free daily generations and realtime canvas draws; $30/mo Pro',
    export_formats: ['Real-time Video', 'High-res PNG', 'Upscaled 4K'],
    documentation_url: 'https://krea.ai',
    trending_percent: 95,
    best_for: ['Realtime Latent Canvas Drawing', 'AI Video Generation', 'Extreme Detail Upscaling'],
    type: 'tool',
    description: 'Real-time generative canvas transforming rough digital brushstrokes into high-definition art instantly.',
  },

  // ═══════════════════════════════════════════════════════════════
  // VIDEO (15 tools)
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Runway',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 125 one-time generation credits; plans from $12/month',
    export_formats: ['MP4', 'ProRes', '4K Upscaled'],
    documentation_url: 'https://docs.runwayml.com',
    trending_percent: 98,
    best_for: ['Gen-3 Alpha Cinema Quality', 'Camera Motion Control', 'Motion Brush Manipulation'],
    type: 'tool',
    description: 'Hollywood-grade generative video suite featuring Gen-3 Alpha, motion brushes, and camera trajectory controls.',
  },
  {
    name: 'Pika',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 30 daily credits; $10/mo Standard subscription',
    export_formats: ['MP4', 'High-FPS Video'],
    documentation_url: 'https://pika.art/docs',
    trending_percent: 92,
    best_for: ['Special Effects (Pikaffects)', 'Lip Sync Integration', 'Image Animation'],
    type: 'tool',
    description: 'Creative video generator popular for fluid animation, lip-syncing, and experimental physics effects.',
  },
  {
    name: 'Sora',
    category: 'Video',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: 'Included with ChatGPT Plus ($20/mo) and Pro ($200/mo) memberships',
    export_formats: ['1080p MP4', 'Video Clips up to 20s'],
    documentation_url: 'https://openai.com/sora',
    trending_percent: 99,
    best_for: ['World Physics Simulation', 'Long Continuous Takes', 'Photorealistic Cinematography'],
    type: 'tool',
    description: 'OpenAI flagship video generation model simulating real-world physics and camera angles with high fidelity.',
  },
  {
    name: 'Descript',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 1 hour of transcription and 720p watermarked video exports',
    export_formats: ['MP4', 'WAV', 'Final Cut XML', 'Premiere Pro Sync'],
    documentation_url: 'https://help.descript.com',
    trending_percent: 93,
    best_for: ['Edit Video via Text Transcript', 'Studio Sound Audio Cleanup', 'Eye Contact Correction'],
    type: 'tool',
    description: 'Video and podcast editing tool allowing creators to cut and re-arrange video by editing the text transcript.',
  },
  {
    name: 'CapCut',
    category: 'Video',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free tier with extensive templates and auto-captions; Pro at $9.99/month',
    export_formats: ['MP4', 'MOV', 'TikTok Direct Share', '4K 60fps'],
    documentation_url: 'https://www.capcut.com/support',
    trending_percent: 95,
    best_for: ['Viral Short-form Edits', 'Automated Subtitle Styles', 'TikTok & Reels Integration'],
    type: 'tool',
    description: 'ByteDance all-in-one video editing platform packed with AI captions, background removals, and templates.',
  },
  {
    name: 'HeyGen',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 1 free credit (1 minute of video); Creator plans from $29/mo',
    export_formats: ['MP4 1080p', 'Interactive Web Embed'],
    documentation_url: 'https://docs.heygen.com',
    trending_percent: 94,
    best_for: ['Lifelike Human Avatars', 'Multi-language Video Translation', 'Corporate Spokespersons'],
    type: 'tool',
    description: 'Avatar video platform generating hyper-realistic synthetic humans speaking with accurate lip sync across 40+ languages.',
  },
  {
    name: 'Synthesia',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free demo video creation; Starter plan from $22/month',
    export_formats: ['MP4', 'SCORM E-learning Packages'],
    documentation_url: 'https://support.synthesia.io',
    trending_percent: 91,
    best_for: ['Enterprise Training Videos', 'SCORM Compliant Modules', '140+ Synthetic Presenters'],
    type: 'tool',
    description: 'Enterprise AI video communications platform for creating employee onboarding and training media with digital avatars.',
  },
  {
    name: 'D-ID',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: '14-day free trial with 5 credits; subscriptions from $5.90/month',
    export_formats: ['MP4', 'Real-time Streaming API'],
    documentation_url: 'https://docs.d-id.com',
    trending_percent: 87,
    best_for: ['Photo to Talking Face', 'Interactive Chatbot Video Agents', 'API Real-time Stream'],
    type: 'tool',
    description: 'Transforms single still portrait photos into speaking digital presenters with real-time streaming APIs.',
  },
  {
    name: 'Colossyan',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free trial with 5 minutes of video; Starter subscription from $27/mo',
    export_formats: ['MP4', 'PDF to Video Converter'],
    documentation_url: 'https://help.colossyan.com',
    trending_percent: 83,
    best_for: ['Workplace Learning & Development', 'PDF to Interactive Video', 'Multi-avatar Conversations'],
    type: 'tool',
    description: 'AI video creator for corporate learning, enabling multi-avatar dialogues and automatic translation.',
  },
  {
    name: 'Elai.io',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free 1-minute credit trial upon account creation; Basic plan from $23/mo',
    export_formats: ['MP4', 'HTML5 Embed'],
    documentation_url: 'https://elai.io/faq',
    trending_percent: 80,
    best_for: ['Article to Video Automation', 'Custom Voice Clones', 'Multi-lingual Presenters'],
    type: 'tool',
    description: 'Generates avatar-led explainer videos directly from blog posts, URLs, and slide decks in minutes.',
  },
  {
    name: 'Pictory',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free trial allowing 3 video projects up to 10 minutes each; Standard from $19/mo',
    export_formats: ['MP4 (16:9, 9:16, 1:1)', 'Subtitle SRT'],
    documentation_url: 'https://pictory.ai/knowledge-base',
    trending_percent: 84,
    best_for: ['Long-form to Short Clips', 'Auto Caption Extraction', 'Stock Video Synchronization'],
    type: 'tool',
    description: 'Automatically extracts short shareable video highlights from long webinars, podcasts, and zoom meetings.',
  },
  {
    name: 'InVideo',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 10 mins/week of AI generation (watermarked); Plus from $20/mo',
    export_formats: ['MP4 1080p', 'YouTube / TikTok Presets'],
    documentation_url: 'https://help.invideo.io',
    trending_percent: 88,
    best_for: ['Text Prompt to Complete Video', 'Voiceover + B-Roll Assembly', 'Faceless Channel Content'],
    type: 'tool',
    description: 'Generates complete narrated videos complete with scripts, voiceovers, B-roll footage, and background tracks.',
  },
  {
    name: 'Fliki',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 5 minutes of monthly credits (watermarked); Standard at $28/mo',
    export_formats: ['MP4', 'Audio Podcast MP3'],
    documentation_url: 'https://fliki.ai/docs',
    trending_percent: 85,
    best_for: ['Text-to-Video Pipelines', 'Podcast Video Visualizers', '2,000+ Realistic Voices'],
    type: 'tool',
    description: 'Combines text-to-speech synthetic voices with dynamic video footage to produce video shorts in minutes.',
  },
  {
    name: 'Lumen5',
    category: 'Video',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free Community plan with 5 monthly videos in 720p; Basic from $19/mo',
    export_formats: ['MP4', 'Social Templates'],
    documentation_url: 'https://support.lumen5.com',
    trending_percent: 81,
    best_for: ['Marketing Social Storyboards', 'Blog Repurposing', 'Template-driven Assembly'],
    type: 'tool',
    description: 'Storyboarding platform built for enterprise marketing teams to turn written blog posts into social video campaigns.',
  },
  {
    name: 'Kapwing',
    category: 'Video',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free tier with 7-minute video export limit (watermarked); Pro from $16/mo',
    export_formats: ['MP4', 'GIF', 'MP3', 'SRT'],
    documentation_url: 'https://www.kapwing.com/help',
    trending_percent: 86,
    best_for: ['Collaborative Cloud Studio', 'Auto Smart Subtitles', 'Meme & Reaction Videos'],
    type: 'tool',
    description: 'Cloud-native collaborative video editor offering smart subtitles, background noise removal, and timeline tools.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AUDIO (15 tools)
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'ElevenLabs',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 10,000 characters per month; Starter plan starts at $5/mo',
    export_formats: ['MP3', 'WAV 44.1kHz', 'PCM Audio Stream'],
    documentation_url: 'https://elevenlabs.io/docs',
    trending_percent: 98,
    best_for: ['Emotional Voice Cloning', 'Sound Effects Generation', 'Real-time Conversational Voice'],
    type: 'tool',
    description: 'Industry-standard voice synthesis platform capable of generating nuanced human emotional tone and accents.',
  },
  {
    name: 'Suno',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 50 daily credits (10 songs); Pro plan at $10/mo for 2,500 credits',
    export_formats: ['MP3', 'WAV', 'Video Music Clips'],
    documentation_url: 'https://suno.com/faqs',
    trending_percent: 97,
    best_for: ['Complete Full-length Songs', 'Vocal + Instrumental Generation', 'Any Musical Genre'],
    type: 'tool',
    description: 'Generates full songs complete with original vocals, harmonies, and instrumentals from simple text prompts.',
  },
  {
    name: 'Udio',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 10 daily credits; Standard plan at $10/month',
    export_formats: ['MP3', 'WAV', 'Track Stems'],
    documentation_url: 'https://www.udio.com/faq',
    trending_percent: 94,
    best_for: ['Complex Musical Composition', 'Stem Separation & Extension', 'Vocal Articulation'],
    type: 'tool',
    description: 'Music synthesis platform founded by former DeepMind researchers praised for fidelity and harmonic complexity.',
  },
  {
    name: 'Adobe Podcast',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free Enhance Speech web tool up to 1 hour/day; Express Premium from $9.99/mo',
    export_formats: ['WAV', 'MP3'],
    documentation_url: 'https://podcast.adobe.com/faq',
    trending_percent: 91,
    best_for: ['Studio Sound Restoration', 'Echo & Room Noise Cancellation', 'Microphone Setup Checker'],
    type: 'tool',
    description: 'Free AI enhancement tool that eliminates room echo and ambient noise to make laptop audio sound like a studio.',
  },
  {
    name: 'Murf',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free trial with 10 minutes of voice generation; Creator plan from $23/mo',
    export_formats: ['MP3', 'WAV', 'FLAC'],
    documentation_url: 'https://murf.ai/resources',
    trending_percent: 86,
    best_for: ['Voiceover Sync with Slides', '120+ Voice Variety', 'Corporate Presentations'],
    type: 'tool',
    description: 'Voice generator studio allowing users to customize pitch, speed, and emphasis to match video and slide timing.',
  },
  {
    name: 'Descript Audio',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with Studio Sound and 1 hr transcription; Creator from $12/mo',
    export_formats: ['WAV', 'MP3', 'AAC'],
    documentation_url: 'https://help.descript.com',
    trending_percent: 92,
    best_for: ['Podcast Audio Editing', 'Filler Word Removal', 'Overdub Voice Correction'],
    type: 'tool',
    description: 'All-in-one audio production suite that removes filler words (ums, uhs) and fixes typos via voice synthesis.',
  },
  {
    name: 'AssemblyAI',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with $50 credit balance; pay-as-you-go speech-to-text API',
    export_formats: ['JSON Transcripts', 'SRT / VTT', 'Speaker Diarization'],
    documentation_url: 'https://www.assemblyai.com/docs',
    trending_percent: 90,
    best_for: ['Speech-to-Text API', 'Speaker Diarization', 'Audio Content Moderation'],
    type: 'tool',
    description: 'Production-ready speech AI models for speech-to-text transcription, speaker labels, and sentiment detection.',
  },
  {
    name: 'Whisper',
    category: 'Audio',
    pricing: 'free',
    signup_required: false,
    free_tier_limits: '100% open-source models (Tiny to Large v3) downloadable for local inference',
    export_formats: ['SRT', 'VTT', 'Plain Text', 'JSON'],
    documentation_url: 'https://github.com/openai/whisper',
    trending_percent: 96,
    best_for: ['Free Local Speech Recognition', 'Multi-lingual Transcription', 'Offline Accuracy'],
    type: 'tool',
    description: 'OpenAI groundbreaking open-weights speech recognition model offering near-human transcription accuracy.',
  },
  {
    name: 'Resemble AI',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free trial with web voice builder; plans from $0.006 per second',
    export_formats: ['WAV 48kHz', 'API Stream'],
    documentation_url: 'https://docs.resemble.ai',
    trending_percent: 85,
    best_for: ['Deepfake Detection (Resemble Detect)', 'Real-time Latency Voiceover', 'Dynamic Audio Ads'],
    type: 'tool',
    description: 'Voice platform specializing in rapid voice cloning, multi-language speech dubbing, and deepfake verification.',
  },
  {
    name: 'Play.ht',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 12,500 characters and access to PlayHT2.0 models; $31/mo Creator',
    export_formats: ['MP3', 'WAV'],
    documentation_url: 'https://docs.play.ht',
    trending_percent: 87,
    best_for: ['Conversational Voice AI', 'Low-latency Voice Agents', 'Audiobook Narration'],
    type: 'tool',
    description: 'High-speed voice engine capable of generating conversational dialogue with natural breath pauses and cadence.',
  },
  {
    name: 'Speechify',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free tier with standard reading voices; Premium at $139/year with celebrity voices',
    export_formats: ['Audio Stream', 'MP3 Export'],
    documentation_url: 'https://speechify.com/help',
    trending_percent: 90,
    best_for: ['Text-to-Speech Speed Reading', 'Document Listening', 'Snoop Dogg & Gwyneth Voices'],
    type: 'tool',
    description: 'Leading text-to-speech app that reads aloud articles, books, and PDFs at up to 4.5x playback speed.',
  },
  {
    name: 'WellSaid',
    category: 'Audio',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '7-day free trial with 50 audio downloads; Maker plan from $44/month',
    export_formats: ['WAV', 'MP3 320kbps'],
    documentation_url: 'https://wellsaidlabs.com/resources',
    trending_percent: 83,
    best_for: ['Corporate Voice Consistency', 'Technical Training Narration', 'Studio Quality Pronunciation'],
    type: 'tool',
    description: 'Enterprise voice studio trusted by Fortune 500 companies for clean narration and pronunciation controls.',
  },
  {
    name: 'Podcastle',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with unlimited recording and 3 hours of transcription; Storyteller from $11.99/mo',
    export_formats: ['MP3', 'WAV', 'MP4 Video Podcasts'],
    documentation_url: 'https://podcastle.ai/help',
    trending_percent: 84,
    best_for: ['Remote Interview Recording', 'Magic Dust Audio Enhancement', 'Browser Recording Studio'],
    type: 'tool',
    description: 'Browser-based recording studio that captures studio-quality multi-track audio and cleans noise with Magic Dust.',
  },
  {
    name: 'Auphonic',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: '2 hours of free processed audio per month; recurring monthly credits available',
    export_formats: ['MP3', 'AAC', 'FLAC', 'Broadcast WAV'],
    documentation_url: 'https://auphonic.com/faq',
    trending_percent: 81,
    best_for: ['Broadcast Loudness Normalization', 'Multi-track Leveling', 'Automatic Audio Mastering'],
    type: 'tool',
    description: 'Automated audio post-production service balancing loudness standards (LUFS), filtering, and speech leveling.',
  },
  {
    name: 'Krisp',
    category: 'Audio',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 60 minutes/day of noise cancellation; Pro at $8/month',
    export_formats: ['Virtual Microphone Driver', 'Meeting Transcripts'],
    documentation_url: 'https://help.krisp.ai',
    trending_percent: 89,
    best_for: ['Real-time Call Noise Cancellation', 'Eliminating Dog Barks / Typing', 'Live Meeting Transcripts'],
    type: 'tool',
    description: 'Real-time noise cancellation software that filters out background voices, barking, and keyboard clicks on live calls.',
  },

  // ═══════════════════════════════════════════════════════════════
  // PRESENTATIONS (14 tools)
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Gamma',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 400 initial AI credits; Plus subscription at $8/month',
    free_tier_slide_limit: 10,
    export_formats: ['PDF', 'PPTX (PowerPoint)', 'Webpage Links'],
    documentation_url: 'https://support.gamma.app',
    trending_percent: 97,
    best_for: ['Document to Presentation', 'Responsive Web Decks', 'Interactive Card Format'],
    type: 'tool',
    description: 'Breakthrough presentation maker transforming text documents into polished decks and interactive web pages.',
  },
  {
    name: 'Beautiful.ai',
    category: 'Presentations',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '14-day free trial; Individual Pro subscription starts at $12/month',
    free_tier_slide_limit: null,
    export_formats: ['PPTX', 'PDF', 'Google Slides', 'MP4'],
    documentation_url: 'https://support.beautiful.ai',
    trending_percent: 89,
    best_for: ['Smart Slide Layout Constraints', 'Brand Template Integrity', 'Automated Infographics'],
    type: 'tool',
    description: 'Smart presentation builder applying professional design rules in real-time as content is added to slides.',
  },
  {
    name: 'Canva Presentations',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with thousands of templates and Magic Design; Canva Pro at $12.99/mo',
    free_tier_slide_limit: 50,
    export_formats: ['PPTX', 'PDF', 'MP4 Video', 'PNG'],
    documentation_url: 'https://www.canva.com/help/presentations',
    trending_percent: 96,
    best_for: ['Extensive Design Library', 'Magic Design Prompting', 'Team Collaboration'],
    type: 'tool',
    description: 'Canva intuitive presentation suite featuring Magic Switch, automatic formatting, and extensive visual assets.',
  },
  {
    name: 'Pitch',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with unlimited presentations and basic AI generator; Pro from $20/mo',
    free_tier_slide_limit: 20,
    export_formats: ['PDF', 'PPTX', 'Live Link with Analytics'],
    documentation_url: 'https://pitch.com/docs',
    trending_percent: 91,
    best_for: ['Venture Pitch Decks', 'Viewer Engagement Analytics', 'Modern Design Aesthetic'],
    type: 'tool',
    description: 'Modern deck builder built for startup founders and fast-moving teams with built-in viewer engagement tracking.',
  },
  {
    name: 'Decktopus',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with limited credits; Business plans starting at $9.99/mo',
    free_tier_slide_limit: 8,
    export_formats: ['PDF', 'PPTX', 'Embedded Web Forms'],
    documentation_url: 'https://decktopus.com/help',
    trending_percent: 84,
    best_for: ['Lead Generation Decks', 'Interactive Booking Embeds', 'Automated Voice Narration'],
    type: 'tool',
    description: 'Presentation creator focused on conversion, enabling lead capture forms and calendar booking directly inside decks.',
  },
  {
    name: 'SlidesAI',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with 3 presentations per month; Pro tier at $10/month',
    free_tier_slide_limit: 10,
    export_formats: ['Google Slides Direct Export', 'PPTX', 'PDF'],
    documentation_url: 'https://www.slidesai.io/docs',
    trending_percent: 87,
    best_for: ['Native Google Slides Add-on', 'Text-to-Slides Conversion', 'Educational Summaries'],
    type: 'tool',
    description: 'Google Workspace marketplace add-on converting text paragraphs into structured Google Slides automatically.',
  },
  {
    name: 'Plus AI',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: '7-day free trial on Google Slides & PowerPoint; Basic at $15/month',
    free_tier_slide_limit: 15,
    export_formats: ['Google Slides Native', 'PowerPoint PPTX'],
    documentation_url: 'https://www.plusdocs.com/help',
    trending_percent: 88,
    best_for: ['Enterprise Google Slides Co-pilot', 'Live Snapshot Data Updates', 'Custom Brand Guidelines'],
    type: 'tool',
    description: 'AI slide copilot for PowerPoint and Google Slides that drafts, translates, and rewrites content within your files.',
  },
  {
    name: 'MagicSlides',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free plan with 3 presentations/month up to 6,000 characters; Pro from $12/mo',
    free_tier_slide_limit: 10,
    export_formats: ['Google Slides', 'PPTX', 'PDF'],
    documentation_url: 'https://www.magicslides.app/help',
    trending_percent: 83,
    best_for: ['YouTube URL to Slides', 'Wikipedia/Article to Deck', 'Multi-language Google Slides'],
    type: 'tool',
    description: 'Google Slides add-on that extracts knowledge from YouTube videos, URLs, or documents into illustrated slide decks.',
  },
  {
    name: 'Slidebean',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free basic plan to build presentations; All-Access from $29/mo',
    free_tier_slide_limit: null,
    export_formats: ['PDF', 'PPTX', 'Shareable Pitch Links'],
    documentation_url: 'https://slidebean.com/knowledge-base',
    trending_percent: 85,
    best_for: ['Investor Pitch Decks', 'Financial Modeling Templates', 'Fundraising Storylines'],
    type: 'tool',
    description: 'Pitch deck platform tailored for venture capital fundraising with proven financial models and deck templates.',
  },
  {
    name: 'Powtoon',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free tier with watermarked video presentations; Pro from $20/month',
    free_tier_slide_limit: 12,
    export_formats: ['MP4 Video', 'PPTX', 'GIF', 'PDF'],
    documentation_url: 'https://support.powtoon.com',
    trending_percent: 82,
    best_for: ['Animated Video Presentations', 'Character Explainers', 'Classroom & Onboarding Slides'],
    type: 'tool',
    description: 'Visual communications platform combining cartoon characters, slide mechanics, and animation for video decks.',
  },
  {
    name: 'Genially',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: false,
    free_tier_limits: 'Free tier with unlimited creations and views; Pro from $7.49/month',
    free_tier_slide_limit: 30,
    export_formats: ['Interactive Web Link', 'SCORM', 'PDF', 'Offline HTML'],
    documentation_url: 'https://help.genially.com',
    trending_percent: 86,
    best_for: ['Gamified Interactive Decks', 'Escape Rooms & Quizzes', 'Educational Infographics'],
    type: 'tool',
    description: 'Interactive presentation tool enabling clickable hotspots, gamification badges, and animated infographics.',
  },
  {
    name: 'Visme',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free basic plan with 100MB storage and core templates; Starter at $12.25/mo',
    free_tier_slide_limit: 15,
    export_formats: ['PPTX', 'PDF', 'HTML5', 'MP4'],
    documentation_url: 'https://support.visme.co',
    trending_percent: 88,
    best_for: ['Data Visualization Slides', 'Interactive Charts & Graphs', 'Infographic Presentations'],
    type: 'tool',
    description: 'Design software that specializes in data-dense visual presentations, live chart widgets, and infographics.',
  },
  {
    name: 'Prezi AI',
    category: 'Presentations',
    pricing: 'freemium',
    signup_required: true,
    free_tier_limits: 'Free basic tier with 5 projects; Standard plan starts at $7/month',
    free_tier_slide_limit: 25,
    export_formats: ['Prezi Video', 'PDF', 'Prezi Desktop App'],
    documentation_url: 'https://support.prezi.com',
    trending_percent: 85,
    best_for: ['Zooming Spatial Canvas', 'Prezi Video Overlay on Webcam', 'Non-linear Storytelling'],
    type: 'tool',
    description: 'Spatial presentation canvas with dynamic cinematic zooming transitions and webcam integration.',
  },
  {
    name: 'Storydoc',
    category: 'Presentations',
    pricing: 'paid',
    signup_required: true,
    free_tier_limits: '14-day free trial; Starter plans start at $30/month',
    free_tier_slide_limit: 15,
    export_formats: ['Interactive Mobile Decks', 'Web Links', 'CRM Activity Sync'],
    documentation_url: 'https://storydoc.com/faq',
    trending_percent: 83,
    best_for: ['B2B Sales Proposals', 'Scrollable Deck Experiences', 'HubSpot/Salesforce Tracking'],
    type: 'tool',
    description: 'Interactive web-deck maker built specifically for B2B sales proposals and pitch decks that reads like a website.',
  },
];
