export interface SeedFeedItem {
  id: string;
  category: 'AI' | 'FUNDING' | 'TECH' | 'STARTUP';
  headline: string;
  summary: string;
  source: string;
  source_url: string;
  published_at: Date;
  created_at: Date;
}

const now = Date.now();
const hour = 1000 * 60 * 60;
const minute = 1000 * 60;

export const SEED_FEED_DATA: SeedFeedItem[] = [
  {
    id: 'f-1',
    category: 'AI',
    headline: 'Anthropic Unveils Claude 3.7 Sonnet with Hybrid Reasoning Architecture',
    summary: 'Combines instantaneous response generation with extended step-by-step reasoning modes across complex software architecture tasks.',
    source: 'anthropic.com',
    source_url: 'https://anthropic.com/news/claude-3-7-sonnet',
    published_at: new Date(now - 12 * minute),
    created_at: new Date(now - 12 * minute),
  },
  {
    id: 'f-2',
    category: 'FUNDING',
    headline: 'Cursor Creator Anysphere Raises $60M Series A Led by Andreessen Horowitz',
    summary: 'The developer-first AI code editor reaches a $400M valuation as software engineers migrate en masse to agentic workflows.',
    source: 'techcrunch.com',
    source_url: 'https://techcrunch.com',
    published_at: new Date(now - 34 * minute),
    created_at: new Date(now - 34 * minute),
  },
  {
    id: 'f-3',
    category: 'TECH',
    headline: 'OpenAI Previews Sora Video Generation Architecture with Spatiotemporal Latents',
    summary: 'Technical papers describe how diffusion models trained on video patches act as world simulators with physics-consistent camera motions.',
    source: 'openai.com',
    source_url: 'https://openai.com/research/video-generation-models-as-world-simulators',
    published_at: new Date(now - 1.2 * hour),
    created_at: new Date(now - 1.2 * hour),
  },
  {
    id: 'f-4',
    category: 'AI',
    headline: 'DeepMind Releases Gemini 2.0 Flash with Sub-Second Multimodal Latency',
    summary: 'Google rolls out next-generation real-time voice, live camera understanding, and built-in tool chaining optimized for low-latency production applications.',
    source: 'blog.google',
    source_url: 'https://blog.google/technology/ai/gemini-2',
    published_at: new Date(now - 2.5 * hour),
    created_at: new Date(now - 2.5 * hour),
  },
  {
    id: 'f-5',
    category: 'STARTUP',
    headline: 'Perplexity Launches Pro Search 2.0 with Multi-Step Academic Reasoning',
    summary: 'The AI search engine introduces recursive code execution and computational knowledge engines directly inside citations.',
    source: 'perplexity.ai',
    source_url: 'https://perplexity.ai/blog',
    published_at: new Date(now - 3.8 * hour),
    created_at: new Date(now - 3.8 * hour),
  },
  {
    id: 'f-6',
    category: 'TECH',
    headline: 'Meta Open-Sources Llama 3.3 70B Offering Flagship Performance on Commodity Hardware',
    summary: 'The new lightweight model rivals proprietary frontier models in coding, multilingual comprehension, and structured JSON generation.',
    source: 'ai.meta.com',
    source_url: 'https://ai.meta.com/blog',
    published_at: new Date(now - 5 * hour),
    created_at: new Date(now - 5 * hour),
  },
  {
    id: 'f-7',
    category: 'FUNDING',
    headline: 'ElevenLabs Hits Unicorn Status Following $80M Series B for Multilingual Voice AI',
    summary: 'The synthetic audio company expands its enterprise conversational AI platform with voice cloning and dynamic translation pipelines.',
    source: 'bloomberg.com',
    source_url: 'https://bloomberg.com',
    published_at: new Date(now - 7 * hour),
    created_at: new Date(now - 7 * hour),
  },
  {
    id: 'f-8',
    category: 'AI',
    headline: 'Black Forest Labs Unveils FLUX.1 Open Weights for Next-Gen Text-to-Image',
    summary: 'Built by former Stable Diffusion researchers, FLUX sets new standards in photorealism, typography rendering, and prompt adherence.',
    source: 'blackforestlabs.ai',
    source_url: 'https://blackforestlabs.ai',
    published_at: new Date(now - 9 * hour),
    created_at: new Date(now - 9 * hour),
  },
  {
    id: 'f-9',
    category: 'STARTUP',
    headline: 'Gamma Reaches 20 Million Users Creating AI-Powered Visual Decks and Docs',
    summary: 'The presentation platform demonstrates explosive product-led growth by replacing static slide decks with fluid, responsive interactive web cards.',
    source: 'forbes.com',
    source_url: 'https://forbes.com',
    published_at: new Date(now - 11 * hour),
    created_at: new Date(now - 11 * hour),
  },
  {
    id: 'f-10',
    category: 'TECH',
    headline: 'Mistral Releases Pixtral 12B Vision Model for Document and Diagram Parsing',
    summary: 'The Parisian AI lab releases an open-weight multimodal model with native support for variable image resolutions and complex technical charts.',
    source: 'mistral.ai',
    source_url: 'https://mistral.ai/news',
    published_at: new Date(now - 14 * hour),
    created_at: new Date(now - 14 * hour),
  },
  {
    id: 'f-11',
    category: 'AI',
    headline: 'DeepSeek Releases R1 Open Weights Rivaling OpenAI o1 on Math Benchmarks',
    summary: 'The open reasoning model demonstrates competitive chain-of-thought verification without relying on proprietary reinforcement learning architectures.',
    source: 'deepseek.com',
    source_url: 'https://github.com/deepseek-ai/DeepSeek-R1',
    published_at: new Date(now - 16 * hour),
    created_at: new Date(now - 16 * hour),
  },
  {
    id: 'f-12',
    category: 'FUNDING',
    headline: 'Magic.dev Secures $338M Supercomputing Round to Build 100M Token Context Models',
    summary: 'Investors back the ultra-long context coding assistant targeting full-codebase architectural refactoring without lossy chunking.',
    source: 'techcrunch.com',
    source_url: 'https://techcrunch.com',
    published_at: new Date(now - 18 * hour),
    created_at: new Date(now - 18 * hour),
  },
  {
    id: 'f-13',
    category: 'TECH',
    headline: 'NVIDIA Announces Blackwell Ultra GPUs Delivering 30x Lower Inference Cost for LLMs',
    summary: 'Hardware architectures featuring second-generation FP4 tensor cores enable trillion-parameter models to run on consolidated rack infrastructure.',
    source: 'nvidia.com',
    source_url: 'https://nvidianews.nvidia.com',
    published_at: new Date(now - 21 * hour),
    created_at: new Date(now - 21 * hour),
  },
  {
    id: 'f-14',
    category: 'STARTUP',
    headline: 'Poolside AI Raises $500M Series B for Specialized Software Engineering Foundation Models',
    summary: 'Former GitHub CTO leads development of reinforcement-learned models designed exclusively for verified code compilation.',
    source: 'reuters.com',
    source_url: 'https://reuters.com',
    published_at: new Date(now - 24 * hour),
    created_at: new Date(now - 24 * hour),
  },
  {
    id: 'f-15',
    category: 'AI',
    headline: 'Cohere Launches Command R+ with Fine-Grained Multilingual Retrieval Augmented Generation',
    summary: 'Enterprise RAG model optimized for verifiable citations and hallucination reduction across ten primary global business languages.',
    source: 'cohere.com',
    source_url: 'https://cohere.com/blog',
    published_at: new Date(now - 27 * hour),
    created_at: new Date(now - 27 * hour),
  },
  {
    id: 'f-16',
    category: 'TECH',
    headline: 'Apple Intelligence Integrates On-Device Private Cloud Compute for macOS and iOS',
    summary: 'Apple details end-to-end cryptographic verifiability for cloud workloads processed on custom Apple Silicon server nodes.',
    source: 'apple.com',
    source_url: 'https://security.apple.com/blog/private-cloud-compute',
    published_at: new Date(now - 30 * hour),
    created_at: new Date(now - 30 * hour),
  },
  {
    id: 'f-17',
    category: 'FUNDING',
    headline: 'Cognition AI Raises $175M at $2B Valuation for Devin Autonomous Software Engineer',
    summary: 'The automated engineering platform demonstrates complex issue resolution on real-world open source repositories.',
    source: 'wsj.com',
    source_url: 'https://wsj.com',
    published_at: new Date(now - 34 * hour),
    created_at: new Date(now - 34 * hour),
  },
  {
    id: 'f-18',
    category: 'AI',
    headline: 'Alibaba Releases Qwen 2.5 Coder 32B Matching Top Closed Proprietary Code LLMs',
    summary: 'Open weights coding model achieves breakthrough scores on HumanEval, MultiPL-E, and repository-level code completion tasks.',
    source: 'qwenlm.github.io',
    source_url: 'https://qwenlm.github.io',
    published_at: new Date(now - 38 * hour),
    created_at: new Date(now - 38 * hour),
  },
  {
    id: 'f-19',
    category: 'STARTUP',
    headline: 'Harvey AI Raises $100M Series C to Modernize Legal Research and Contract Drafting',
    summary: 'Law firms across North America and Europe deploy custom-tuned domain models for complex regulatory filings.',
    source: 'techcrunch.com',
    source_url: 'https://techcrunch.com',
    published_at: new Date(now - 42 * hour),
    created_at: new Date(now - 42 * hour),
  },
  {
    id: 'f-20',
    category: 'TECH',
    headline: 'EU AI Act Officially Takes Effect Setting Global Compliance Baseline for Frontier Models',
    summary: 'New regulatory frameworks introduce transparency requirements for high-risk generative systems and synthetic media watermarking.',
    source: 'europa.eu',
    source_url: 'https://digital-strategy.ec.europa.eu',
    published_at: new Date(now - 46 * hour),
    created_at: new Date(now - 46 * hour),
  },
  {
    id: 'f-21',
    category: 'AI',
    headline: 'Microsoft Introduces Phi-4 14B Highlighting Synthetic Data Quality Over Model Size',
    summary: 'Small language model achieves competitive benchmark numbers against models quadruple its parameter count through curated synthetic curriculum training.',
    source: 'microsoft.com',
    source_url: 'https://www.microsoft.com/en-us/research',
    published_at: new Date(now - 50 * hour),
    created_at: new Date(now - 50 * hour),
  },
  {
    id: 'f-22',
    category: 'FUNDING',
    headline: 'Suno Raises $125M Series B as AI-Generated Music Surpasses 100M Streams',
    summary: 'Audio generation startup accelerates audio fidelity development and artist revenue sharing partnerships.',
    source: 'billboard.com',
    source_url: 'https://billboard.com',
    published_at: new Date(now - 54 * hour),
    created_at: new Date(now - 54 * hour),
  },
  {
    id: 'f-23',
    category: 'STARTUP',
    headline: 'Windsurf IDE Crosses 500,000 Active Developers with Collaborative Agent Cascade Flows',
    summary: 'Codeium rolls out multi-developer workspace indexing and autonomous pull-request synthesis directly inside the editor.',
    source: 'codeium.com',
    source_url: 'https://codeium.com/blog',
    published_at: new Date(now - 58 * hour),
    created_at: new Date(now - 58 * hour),
  },
  {
    id: 'f-24',
    category: 'AI',
    headline: 'Kuaishou Kling 1.5 Upgrades High-Motion Video Generation with Native 1080p Export',
    summary: 'Diffusion architecture improves temporal coherence in fast camera pans and dynamic multi-character choreography.',
    source: 'klingai.com',
    source_url: 'https://klingai.com',
    published_at: new Date(now - 62 * hour),
    created_at: new Date(now - 62 * hour),
  },
  {
    id: 'f-25',
    category: 'TECH',
    headline: 'Google DeepMind Unveils AlphaFold 3 Predicting Structure of Biological Molecules and Ligands',
    summary: 'Scientific breakthrough opens new avenues in drug discovery by modeling interactions between proteins, DNA, RNA, and small molecules.',
    source: 'nature.com',
    source_url: 'https://nature.com',
    published_at: new Date(now - 66 * hour),
    created_at: new Date(now - 66 * hour),
  },
  {
    id: 'f-26',
    category: 'FUNDING',
    headline: 'Glean Secures $260M Series E at $4.6B Valuation for Enterprise AI Knowledge Work',
    summary: 'Workplace search and automation platform connects enterprise SaaS repositories with permission-aware semantic graphs.',
    source: 'venturebeat.com',
    source_url: 'https://venturebeat.com',
    published_at: new Date(now - 70 * hour),
    created_at: new Date(now - 70 * hour),
  },
  {
    id: 'f-27',
    category: 'AI',
    headline: 'Runway Partners with Major Film Studios to Deploy Gen-3 Alpha in Visual Effects Workflows',
    summary: 'Virtual production pipelines adopt neural scene synthesis for environmental set extensions and previz sequences.',
    source: 'hollywoodreporter.com',
    source_url: 'https://hollywoodreporter.com',
    published_at: new Date(now - 75 * hour),
    created_at: new Date(now - 75 * hour),
  },
  {
    id: 'f-28',
    category: 'STARTUP',
    headline: 'Braintrust Raises $36M for AI Evaluation Infrastructure and Real-Time Telemetry',
    summary: 'Enterprise engineering teams standardize automated regression testing and evals for LLM prompts and pipelines.',
    source: 'braintrust.dev',
    source_url: 'https://braintrust.dev',
    published_at: new Date(now - 80 * hour),
    created_at: new Date(now - 80 * hour),
  },
  {
    id: 'f-29',
    category: 'TECH',
    headline: 'AWS Bedrock Expands Guardrails with Real-Time Contextual Hallucination Detection',
    summary: 'Cloud infrastructure adds automated checks verifying that model responses map strictly to grounded reference documents.',
    source: 'aws.amazon.com',
    source_url: 'https://aws.amazon.com/bedrock',
    published_at: new Date(now - 85 * hour),
    created_at: new Date(now - 85 * hour),
  },
  {
    id: 'f-30',
    category: 'AI',
    headline: 'Stability AI Releases Stable Audio 2.0 with Full Track Synthesis and Audio-to-Audio',
    summary: 'Music generation model produces up to three minutes of structured stereo audio with intro, verse, chorus, and outro progression.',
    source: 'stability.ai',
    source_url: 'https://stability.ai',
    published_at: new Date(now - 90 * hour),
    created_at: new Date(now - 90 * hour),
  },
  {
    id: 'f-31',
    category: 'FUNDING',
    headline: 'Physical Intelligence Raises $400M Seed Round to Build Universal Robot Brain Models',
    summary: 'Robot foundation models demonstrate transfer learning across manipulation tasks on multiple disparate robotic arms.',
    source: 'nytimes.com',
    source_url: 'https://nytimes.com',
    published_at: new Date(now - 95 * hour),
    created_at: new Date(now - 95 * hour),
  },
  {
    id: 'f-32',
    category: 'STARTUP',
    headline: 'Lovable AI Crosses $10M ARR in Three Months Generating Full-Stack Production Web Apps',
    summary: 'Developer platform pairs conversational specifications with instant GitHub deployment, Supabase backend, and Stripe billing.',
    source: 'lovable.dev',
    source_url: 'https://lovable.dev',
    published_at: new Date(now - 100 * hour),
    created_at: new Date(now - 100 * hour),
  },
  {
    id: 'f-33',
    category: 'TECH',
    headline: 'vLLM Consortium Adds Chunked Prefill and PagedAttention v3 Slashing Server Memory 40%',
    summary: 'Open source inference engine enables continuous batching optimizations for enterprise hosting clusters.',
    source: 'vllm.ai',
    source_url: 'https://blog.vllm.ai',
    published_at: new Date(now - 106 * hour),
    created_at: new Date(now - 106 * hour),
  },
  {
    id: 'f-34',
    category: 'AI',
    headline: 'Google Releases Gemma 2 2B with Advanced Knowledge Distillation from 27B Parameters',
    summary: 'Lightweight model runs smoothly on edge smartphones and browser WebGPU environments without noticeable quantization loss.',
    source: 'developers.googleblog.com',
    source_url: 'https://developers.googleblog.com',
    published_at: new Date(now - 112 * hour),
    created_at: new Date(now - 112 * hour),
  },
  {
    id: 'f-35',
    category: 'FUNDING',
    headline: 'Hebbia Raises $130M Series B Led by Andreessen Horowitz for Matrix AI Search',
    summary: 'Financial institutions and sovereign wealth funds automate complex SEC 10-K and due diligence document synthesis.',
    source: 'techcrunch.com',
    source_url: 'https://techcrunch.com',
    published_at: new Date(now - 118 * hour),
    created_at: new Date(now - 118 * hour),
  },
  {
    id: 'f-36',
    category: 'STARTUP',
    headline: 'Bolt.new Introduces WebContainers Running Full Node.js and Next.js Stacks in Web Browsers',
    summary: 'StackBlitz rolls out complete in-browser sandboxing enabling instant full-stack web application compilation without servers.',
    source: 'stackblitz.com',
    source_url: 'https://blog.stackblitz.com',
    published_at: new Date(now - 124 * hour),
    created_at: new Date(now - 124 * hour),
  },
  {
    id: 'f-37',
    category: 'TECH',
    headline: 'Cloudflare Launches Workers AI Dynamic Speculative Decoding for 2x Faster TTFT',
    summary: 'Edge computing network pairs small draft models with large foundation models to double token output throughput.',
    source: 'blog.cloudflare.com',
    source_url: 'https://blog.cloudflare.com',
    published_at: new Date(now - 130 * hour),
    created_at: new Date(now - 130 * hour),
  },
  {
    id: 'f-38',
    category: 'AI',
    headline: 'Mistral Open-Sources Codestral 22B Specialized in Multi-File Repo Synthesis and Fill-in-the-Middle',
    summary: 'Fast 80+ language coding model features native 32K context window and unmatched FIM code completion accuracy.',
    source: 'mistral.ai',
    source_url: 'https://mistral.ai/news/codestral',
    published_at: new Date(now - 136 * hour),
    created_at: new Date(now - 136 * hour),
  },
  {
    id: 'f-39',
    category: 'FUNDING',
    headline: 'Sierra AI Raises $175M at $4.5B Valuation for Enterprise Customer Experience Agents',
    summary: 'Bret Taylor and Clay Bavor scale autonomous brand agents resolving complex customer requests across retail and banking.',
    source: 'reuters.com',
    source_url: 'https://reuters.com',
    published_at: new Date(now - 142 * hour),
    created_at: new Date(now - 142 * hour),
  },
  {
    id: 'f-40',
    category: 'STARTUP',
    headline: 'Writer Announces Palmyra-Creative Delivering Consistent Tone across 50 Enterprise Brands',
    summary: 'Generative AI platform guarantees brand guideline adherence and automated factual verification for marketing campaigns.',
    source: 'writer.com',
    source_url: 'https://writer.com/blog',
    published_at: new Date(now - 148 * hour),
    created_at: new Date(now - 148 * hour),
  },
  {
    id: 'f-41',
    category: 'TECH',
    headline: 'PostgreSQL 17 Integrates Native Vector Indexing Enhancements for Hybrid Semantic Search',
    summary: 'Database upgrade improves pgvector performance 400% on high-dimensional embeddings for enterprise RAG architectures.',
    source: 'postgresql.org',
    source_url: 'https://www.postgresql.org/about/news',
    published_at: new Date(now - 154 * hour),
    created_at: new Date(now - 154 * hour),
  },
  {
    id: 'f-42',
    category: 'AI',
    headline: 'Cohere Releases Aya 101 Multilingual Open Weights Covering 101 Global Languages',
    summary: 'Nonprofit research collective releases state-of-the-art model bridging digital language divides in African, Asian, and indigenous dialects.',
    source: 'cohere.com',
    source_url: 'https://cohere.com/research/aya',
    published_at: new Date(now - 160 * hour),
    created_at: new Date(now - 160 * hour),
  },
  {
    id: 'f-43',
    category: 'FUNDING',
    headline: 'Figure AI Raises $675M for Humanoid Robots with Integrated OpenAI Natural Language Control',
    summary: 'Commercial trials begin deployment of autonomous humanoids handling logistics and assembly line work in automotive plants.',
    source: 'bloomberg.com',
    source_url: 'https://bloomberg.com',
    published_at: new Date(now - 166 * hour),
    created_at: new Date(now - 166 * hour),
  },
  {
    id: 'f-44',
    category: 'STARTUP',
    headline: 'Tavily Launches Unified Search API Designed Exclusively for LLM Agents and Real-Time RAG',
    summary: 'Search engine removes web crawler bloat and boilerplate, delivering clean factual snippets with primary domain verification.',
    source: 'tavily.com',
    source_url: 'https://tavily.com',
    published_at: new Date(now - 172 * hour),
    created_at: new Date(now - 172 * hour),
  },
  {
    id: 'f-45',
    category: 'TECH',
    headline: 'OpenAI Releases Realtime API for Low-Latency Speech-to-Speech Streaming',
    summary: 'WebSocket API combines audio input, multimodal reasoning, and natural emotional cadence output into a single low-latency roundtrip.',
    source: 'openai.com',
    source_url: 'https://platform.openai.com/docs/guides/realtime',
    published_at: new Date(now - 178 * hour),
    created_at: new Date(now - 178 * hour),
  },
  {
    id: 'f-46',
    category: 'AI',
    headline: 'Databricks Releases DBRX 132B Open MoE Model Outperforming Llama 2 70B and Mixtral',
    summary: 'Mixture-of-experts model activates 36B parameters per token for accelerated training and high-throughput corporate deployments.',
    source: 'databricks.com',
    source_url: 'https://www.databricks.com/blog/introducing-dbrx-new-state-of-the-art-open-llm',
    published_at: new Date(now - 184 * hour),
    created_at: new Date(now - 184 * hour),
  },
  {
    id: 'f-47',
    category: 'FUNDING',
    headline: 'LangChain Secures $25M Series A to Build LangSmith Observability Platform',
    summary: 'Developer platform introduces production tracing, regression test suites, and prompt playground tools for agentic chains.',
    source: 'techcrunch.com',
    source_url: 'https://techcrunch.com',
    published_at: new Date(now - 190 * hour),
    created_at: new Date(now - 190 * hour),
  },
  {
    id: 'f-48',
    category: 'STARTUP',
    headline: 'Upstash Introduces Vector and QStash for Serverless AI Message Streaming and Embeddings',
    summary: 'Serverless data platform allows developers to run semantic similarity queries at edge with zero cold start latency.',
    source: 'upstash.com',
    source_url: 'https://upstash.com/blog',
    published_at: new Date(now - 196 * hour),
    created_at: new Date(now - 196 * hour),
  },
  {
    id: 'f-49',
    category: 'TECH',
    headline: 'Anthropic Introduces Prompt Caching Reducing Claude API Latency up to 80% and Costs 90%',
    summary: 'Developers caching long documentation, code repositories, and book-length context windows experience sub-second responses on repeated calls.',
    source: 'anthropic.com',
    source_url: 'https://docs.anthropic.com/en/docs/prompt-caching',
    published_at: new Date(now - 202 * hour),
    created_at: new Date(now - 202 * hour),
  },
  {
    id: 'f-50',
    category: 'AI',
    headline: 'Pika 2.0 Launches Custom Effects and Realistic Physical Simulation for Dynamic Video Shots',
    summary: 'Creators gain direct slider controls over object deflation, explosion, liquefaction, and realistic camera velocity dynamics.',
    source: 'pika.art',
    source_url: 'https://pika.art/blog',
    published_at: new Date(now - 208 * hour),
    created_at: new Date(now - 208 * hour),
  },
  {
    id: 'f-51',
    category: 'FUNDING',
    headline: 'Character.AI Signs Non-Exclusive Tech Licensing Agreement with Google in $2.5B Deal',
    summary: 'Founders Noam Shazeer and Daniel De Freitas rejoin Google DeepMind to focus on next-generation reasoning architectures.',
    source: 'reuters.com',
    source_url: 'https://reuters.com',
    published_at: new Date(now - 214 * hour),
    created_at: new Date(now - 214 * hour),
  },
  {
    id: 'f-52',
    category: 'TECH',
    headline: 'Groq Delivers 1,000 Tokens Per Second Inference on Llama 3 Using LPUs (Language Processing Units)',
    summary: 'Custom tensor streaming silicon eliminates external DRAM bottlenecks, enabling instant multi-step agent tool execution in production.',
    source: 'groq.com',
    source_url: 'https://groq.com/news',
    published_at: new Date(now - 220 * hour),
    created_at: new Date(now - 220 * hour),
  },
];
